import React from 'react'
import Link from 'next/link'
import Head from 'next/head'


export default function delivery() {
  return (
    <div>
     <Head>
        <title>DELIVERY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
     </Head>
    
      <Link href="/">
        <a>Back to home</a>
      </Link>
  
  </div>
  )
}
